[package]
name = "faas-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
sqlx = {version="0.8.6", features=["runtime-tokio-native-tls", "sqlite"]}
tokio = { version = "1.48.0", features = ["full"] }
wasmtime = "38.0.4"
